
  <!-- ====================================
  ———	HOME SECTION
  ===================================== -->
  <section class="home-bg" style="background-image: url(<?= $wwwUrl ?>/images/background/background-img-3.jpg); ">
    <div class="container">
      <div class="home-holder">
        <div>
          <h1 class="home-title">Bienvenue à la crèche des petits Amis !</h1>
          <span class="home-element">
            <p> Vous y trouverez les informations nécessaires concernant notre structure.</p>
          </span>
          <span class="home-element">
            <p> <a class="btn btn-primary" href="<?= $requestUrl ?>/user/signin">Besoin d'un mode de garde? <br/>Inscrivez-vous</a></p>
          </span>
        </div>
      </div>
    </div>
  </section>

