<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Affichage du template lié à la vue -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/coca.jpg" alt="">
            </td>
            <td>
                <strong>Coca-cola</strong>
                <br>
                "Coca-cola diet of course.... count on me = "more sugar"
            </td>
            <td>
                <strong>3.00€</strong>
            </td>
        </tr>
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/bagel_thon.jpg" alt="">
            </td>
            <td>
                <strong>"Bagel-thon"</strong>
                <br>
                "Il vous est possible de remplacer le tartare de légumes d’été par une ratatouille bien épicée,
                un caviar d’aubergines, une tapenade d’olives noires, une tapenade de poivrons rouge ou bien
                d’autres préparations à base de légumes !"
            </td>
            <td>
                <strong>6.00€</strong>
            </td>
        </tr>
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/bacon_cheeseburger.jpg" alt="">
            </td>
            <td>
                <strong>"Bacon Cheeseburger"</strong>
                <br>
                "Vous pouvez remplacer le cheddar par de vrai tranche d'emmental pour le rendre plus frenchie !
                - Vous pouvez remplacer la moutarde par de la béarnaise. - Pour plaire à tous, vous pouvez
                mettre des tranches de tomates, des oignons, des cornichons, etc..."
            </td>
            <td>
                <strong>13.00€</strong>
            </td>
        </tr>
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/carrot_cake.jpg" alt="">
            </td>
            <td>
                <strong>"Carrot Cake"</strong>
                <br>
                "Le gâteau aux carottes est une spécialité suisse originaire du canton d'Argovie. Il est
                également connu dans le monde anglo-saxon, comme carrot cake. Aux États-Unis, il est célébré
                chaque 3 février, à l'occasion du National Carrot Cake Day"
            </td>
            </td>
            <td>
                <strong>7.00€</strong>
            </td>
        </tr>
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/chocolate_donut.jpg" alt="">
            </td>
            <td>
                <strong>"Chocolate Donut"</strong>
                <br>
                "Les donuts, ou beignes, peuvent parfois être fourrés d’une préparation crémeuse, ce qui les
                apparentent au zeppola (it) italien4, ou encore de confiture. Ils s’accompagnent généralement
                d’un café. Les petits donuts de forme sphérique sont appelés donut holes"
            </td>
            <td>
                <strong>5.00€</strong>
            </td>
        </tr>
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/drpepper.jpg" alt="">
            </td>
            <td>
                <strong>"Dr Pepper"</strong>
                <br>
                "Super boisson sans le soucre"
            </td>
            </td>
            <td>
                <strong>3.00€</strong>
            </td>
        </tr>
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/milkshake.jpg" alt="">
            </td>
            <td>
                <strong>"Milkshake"</strong>
                <br>
                "Très frais, excellent boisson pour perdre du pois, on vous le recomende vivement ;)"
            </td>
            <td>
                <strong>10.00€</strong>
            </td>
        </tr>
    </tbody>
</table>