<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Crèche les P'tits amis</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">-->
     <!-- Custom css -->
    <link href="<?= $wwwUrl ?>/css/nursery.css"  id="option_style" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=El+Messiri|Kaushan+Script&display=swap">
    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>
</head>

<body>

  <!-- ====================================
  ——— En-tête commune
  ===================================== -->
<div>
  <header class="header" id="pageTop">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-scrollUp navbar-sticky navbar-white">
      <div class="container">
        <a class="navbar-brand" href="<?= $requestUrl ?>">
          <img class="d-inline-block" src="<?= $wwwUrl ?>/images/logo-nursery.png" alt="Crèches les p'tits amis">
        </a>

        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav ml-lg-auto">
            <li class="nav-item dropdown bg-warning">
              <a class="nav-link dropdown-toggle  active " href="<?= $requestUrl ?>">
                <i class="fa fa-home nav-icon" aria-hidden="true"></i>
                <span>Accueil</span>
              </a>
            </li>
            <li class="nav-item dropdown bg-purple">
              <a class="nav-link dropdown-toggle " href="javascript:void(0)" id="stores"
                role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-calendar nav-icon" aria-hidden="true"></i>
                <span>Actualités</span>
              </a>
            </li>

            <?php if($userSession->isAuthenticated() == true): ?>
              <li class="nav-item dropdown bg-danger">
                <a class="nav-link dropdown-toggle " href="javascript:void(0)" role="button"
                  data-toggle="dropdown">
                  <i class="fa fa-list-ul nav-icon" aria-hidden="true"></i>
                  <span>Demandes</span>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item" href="<?= $requestUrl ?>/user/nursery/requestEdit">Inscrire mon enfant</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="<?= $requestUrl ?>/user/nursery/requestList">Mes demandes</a>
                  </li>
                </ul>
              </li>

              <li class="nav-item dropdown bg-info">
                <a class="nav-link dropdown-toggle " href="javascript:void(0)" id="stores"
                  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-pencil-square-o nav-icon" aria-hidden="true"></i>
                  <span>Facturation</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="stores">
                  <li>
                    <a class="dropdown-item " href="product-single.html">Paiement</a>
                  </li>
                  <li>
                    <a class="dropdown-item " href="product-category.html">Vos factures</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown mega-dropdown bg-success">
                <a class="nav-link dropdown-toggle " href="#" role="button"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fa fa-file-text-o nav-icon" aria-hidden="true"></i>
                  <!-- show user profile(with lastName and FirstName), modify my profile -->
                  <span>Bonjour <?= $userSession->getFirstName() ?></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="stores">
                  <li>
                    <a href="<?= $requestUrl ?>/user/profile" class="dropdown-item">Votre profil</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="<?= $requestUrl ?>/user/logout">Se déconnecter</a>
                  </li>
                </ul>
              </li>
            <?php else: ?>

              <li class="nav-item dropdown mega-dropdown bg-success">
                <a class="nav-link dropdown-toggle" href="<?= $requestUrl ?>/user/login">
                  <i class="fa fa-file-text-o nav-icon" aria-hidden="true"></i>
                  <span>Se connecter</span>
                </a>
              </li>
            <?php endif; ?>
          </ul>
        </div>
      </div>
    </nav>
  </header>

    <main id="wrapper">
      <div id="content">
          <!-- Affichage du template lié à la vue -->
          <?php include $this->viewData['template'] ?>
      </div>
</main>

    <!-- Pied de page commun -->
    <!--
    <footer id="footer">
          <ul class="link-list">
              <small>Suivez-nous sur</small>
              <li><a href="https://github.com/akiryluk/nursery/"><i class="fa fa-github-square fa-2x"></i></a></li>
              <li><a href="https://linkedin.com/in/anna-maria-kiryluk/"><i class="fa fa-linkedin fa-2x"></i></a></li>
              <li><a href="https://facebook.com/ania.kiryluk.7/"><i class="fa fa-facebook-square fa-2x"></i></a></li>
          </ul>

          <small>Réalisé avec <i class="fa fa-compass fa-2x"></i> par Ania</small>
    </footer>
-->
    <footer class="footer-bg-img">
  <!-- Footer Color Bar -->
  <div class="color-bar">
    <div class="container-fluid">
      <div class="row">
        <div class="col color-bar bg-warning"></div>
        <div class="col color-bar bg-danger"></div>
        <div class="col color-bar bg-success"></div>
        <div class="col color-bar bg-info"></div>
        <div class="col color-bar bg-purple"></div>
        <div class="col color-bar bg-pink"></div>
        <div class="col color-bar bg-warning d-none d-md-block"></div>
        <div class="col color-bar bg-danger d-none d-md-block"></div>
        <div class="col color-bar bg-success d-none d-md-block"></div>
        <div class="col color-bar bg-info d-none d-md-block"></div>
        <div class="col color-bar bg-purple d-none d-md-block"></div>
        <div class="col color-bar bg-pink d-none d-md-block"></div>
      </div>
    </div>
  </div>
  <!-- Copy Right -->
  <div class="copyright">
    <div class="container">
      <div class="row py-4 align-items-center">
        <div class="col-sm-7 col-xs-12 order-1 order-md-0">
          <p class="copyright-text"> Réalisé avec <i class="fa fa-heart fa-2x"></i> par <a href="https://linkedin.com/in/anna-maria-kiryluk/" target="_blank">Anna Kiryluk.</a></p>
        </div>

        <div class="col-sm-5 col-xs-12">
          <ul class="list-inline d-flex align-items-center justify-content-md-end justify-content-center mb-md-0">
            <li class="mr-3">
              <a class="icon-rounded-circle-small bg-danger" href="https://github.com/akiryluk/nursery/">
                <i class="fa fa-github text-white" aria-hidden="true"></i>
              </a>
            </li>
            <li class="mr-3">
              <a class="icon-rounded-circle-small bg-success" href="https://linkedin.com/in/anna-maria-kiryluk/">
                <i class="fa fa-linkedin text-white" aria-hidden="true"></i>
              </a>
            </li>
            <li class="mr-3">
              <a class="icon-rounded-circle-small bg-warning" href="https://facebook.com/ania.kiryluk.7/">
                <i class="fa fa-facebook text-white" aria-hidden="true"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>


    <div class="scrolling">
      <a href="#pageTop" class="back-to-top" id="back-to-top" style="opacity: 1;">
        <i class="fa fa-arrow-up" aria-hidden="true"></i>
      </a>
    </div>
    <!-- Code principal JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>

</html>