<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Crèche les P'tits amis</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <script src="<?= $wwwUrl ?>/js/classes/FormValidator.class.js"></script>
</head>

<body>

    <!-- En-tête commune -->
    <header>
        <h1>
            <a href="<?= $requestUrl ?>">
                <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="">Little dev nursery!
            </a>
        </h1>
    </header>

    <!-- Interface utilisateur -->
    <nav class="user-interface">
        <ul class="link-list">
            <?php if($userSession->isAdmin() == true): ?>
                <li>
                    <a class="button button-primary" href="<?= $requestUrl ?>/admin">Admin</a>
                    <a class="button button-primary" href="<?= $requestUrl ?>/admin/Meal">Meal</a>
                    <a class="button button-primary" href="<?= $requestUrl ?>/admin/user">Admin user</a>
                    <a class="button button-primary" href="<?= $requestUrl ?>/booking">Réserver</a>
                    <a class="button button-primary" href="<?= $requestUrl ?>/order">Commander</a>
                </li>
                <li class="layout-right">
                    <p class="welcome">Bonjour <strong><?= $userSession->getFullName() ?></strong> !</p>
                    <a class="button button-primary" href="<?= $requestUrl ?>/user/logout">Déconnexion</a>
                </li>
            <?php elseif($userSession->isAuthenticated() == true): ?>
                <li>
                    <a class="button button-primary" href="<?= $requestUrl ?>/booking">Réserver</a>
                    <a class="button button-primary" href="<?= $requestUrl ?>/order">Commander</a>
                </li>
                <li class="layout-right">
                <!-- show user profile(with lastName and FirstName), modify my profile -->
                    <a href="<?= $requestUrl ?>/user/profile"><p class="welcome">Bonjour <strong><?= $userSession->getFullName() ?></strong> !</p></a>                                        
                    <a class="button button-primary" href="<?= $requestUrl ?>/user/logout">Déconnexion</a>
                </li>
        <?php else: ?>
                <li>
                    <a class="button button-primary" href="<?= $requestUrl ?>/user/signin">Créer un compte</a>
                </li>
                <li class="layout-right">
                    <a class="button button-primary" href="<?= $requestUrl ?>/user/login">Connexion</a>
                </li>
            <?php endif; ?>
        </ul>
    </nav>

    <main>
        <!-- Affichage du template lié à la vue -->
        <?php include $this->viewData['template'] ?>
    </main>
    <!-- Pied de page commun -->
    <footer>
        <ul class="link-list">
            <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
            <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
            <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
        </ul>
        <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par Ania</small>
    </footer>

    <!-- Code principal JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>

</html>