<!-- Affichage du template lié à la vue -->
<?php
$isNew = false;
if(empty($nurseryRequest) || empty($nurseryRequest->getId())){
    $isNew = true;
}

?>

<?php if($isNew == true): ?>
<h1> <i class="fa fa-folder fa-2x"></i>  Créer votre demande d'inscription</h1>
<?php else: ?>
    <h1> <i class="fa fa-edit fa-2x"></i>  Editer votre demande d'inscription</h1>
    <!-- Nursery Request Tabs -->
    <ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" href="<?= $requestUrl ?>/user/nursery/requestEdit?id=<?= $nurseryRequest->getId() ?>">Général</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?= $requestUrl ?>/user/nursery/requestTab/kidTabEdit?requestId=<?= $nurseryRequest->getId() ?>">Enfant</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?= $requestUrl ?>/user/nursery/requestTab/mumTabEdit?requestId=<?= $nurseryRequest->getId() ?>"">Maman</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?= $requestUrl ?>/user/nursery/requestTab/fatherTabEdit?requestId=<?= $nurseryRequest->getId() ?>"">Papa</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?= $requestUrl ?>/user/nursery/requestTab/healthTabEdit?requestId=<?= $nurseryRequest->getId() ?>"">Santé</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?= $requestUrl ?>/user/nursery/requestTab/urgencyTabEdit?requestId=<?= $nurseryRequest->getId() ?>"">Urgence</a>
    </li>
    </ul>

<?php endif; ?>


<form class="generic-form" action="<?= $requestUrl ?>/user/nursery/requestEdit" method="POST">
    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !
        </h3>
        <p><?= $errorMessage ?></p>
    </aside>
    <?php if(!empty($infoMessage)): ?>
    <div class="alert alert-success" role="alert">
        <?= $infoMessage ?>
    </div>
    <?php endif; ?>
    <fieldset>
        <legend>
            <h2> <i class="fa fa-info fa-2x"></i>  Info de bases</h2>
        </legend>
        <input id="id" type="hidden" name="id" value="<?= $nurseryRequest->getId() ?>" />
        <input id="kidId" type="hidden" name="kidId" value="<?= $nurseryRequest->getKidId() ?>" />
        <div class="form-group">

        <label for="firstName">Prénom de l'enfant:</label><br>
        <input id="firstName" class="form-control" type="text" name="firstName" value="<?= $kidPerson->getFirstName() ?>"/><br>
        <label for="lastName">Nom de l'enfant:</label><br>
        <input id="lastName" class="form-control" type="text" name="lastName" value="<?= $kidPerson->getLastName() ?>"/><br>

        <label for="mumFirstName">Prénom de Maman:</label><br>
        <input id="mumFirstName" class="form-control" type="text" name="mumFirstName" value="<?= $mumPerson->getFirstName() ?>"/><br>
        <label for="mumLastName">Nom de Maman:</label><br>
        <input id="mumLastName" class="form-control" type="text" name="mumLastName" value="<?= $mumPerson->getLastName() ?>"/><br>

        <label for="dadFirstName">Prénom de Papa:</label><br>
        <input id="dadFirstName" class="form-control" type="text" name="dadFirstName" value="<?= $dadPerson->getFirstName() ?>"/><br>
        <label for="dadLastName">Nom de Papa:</label><br>
        <input id="dadLastName" class="form-control" type="text" name="dadLastName" value="<?= $dadPerson->getLastName() ?>"/><br>

        <label for="entryDate">Date d'entrée:</label><br>
        <input id="entryDate" class="form-control" type="text" name="entryDate" data-required data-name="Date d'entrée"
            value="<?= $nurseryRequest->getEntryDate() ?>" />
        <br>
        <label for="cafNumber">Caf number :</label><br>
        <input id="id" class="form-control" type="text" name="cafNumber" value="<?= $nurseryRequest->getCafNumber() ?>" /><br>
<?php if($userSession->isAdmin() == true): ?>
        <label for="cafNumber">Statut de la demande :</label><br>
             <input type="radio" id="enCours" name="groupeSelect">
             <label for="enCours">En cours</label>
             <input type="radio" id="acceptee" name="groupeSelect">
             <label for="acceptee">Acceptée</label><br/>
             <input type="radio" id="refusee" name="groupeSelect">
             <label for="refusee">Refusée</label>
        </div>
<?php endif; ?>
       <!--<?= $nurseryRequest->getStatusReq() ?><br>-->

        <?php if($isNew == true): ?>
            <button class="btn btn-primary" type="submit" name="submitButton">Créer</button>
        <?php else: ?>
            <button class="btn btn-primary" type="submit" name="submitButton">Sauvegarder</button>
        <?php endif; ?>
        <button class="btn btn-primary" type="button" value="Retour" onclick="history.go(-2)">Retour</button>
    </fieldset>
</form>