<!-- Affichage du template lié à la vue -->
<?php
$isNew = false;
if(empty($nurseryRequest) || empty($nurseryRequest->getId())){
    $isNew = true;
}

?>

<aside class="error-message hidden">
    <h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !
    </h3>
    <p><?= $errorMessage ?></p>
</aside>
<?php if(!empty($infoMessage)): ?>
    <div class="alert alert-success" role="alert">
        <?= $infoMessage ?>
    </div>
<?php endif; ?>
<section class="py-8 py-md-7">
    <div class="container">
        <div class="row">
            <div class="col-sm-6  col-lg-12">
                <div class="mb-4 mb-sm-0">
                <div class="bg-warning rounded-top p-2">                  
                    <?php if($isNew == true): ?>
                        <h1 class="text-white font-weight-bold mb-0 ml-2">Créer votre demande d'inscription</h1>
                    <?php else: ?>
                        <h1 class="text-white font-weight-bold mb-0 ml-2">Editer votre demande d'inscription</h1>
                    <?php endif; ?>
                </div>

                <?php if($isNew == false): ?>
                    <!-- Nursery Request Tabs -->
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active"
                                href="<?= $requestUrl ?>/user/nursery/requestEdit?id=<?= $nurseryRequest->getId() ?>">Général</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="<?= $requestUrl ?>/user/nursery/requestTab/kidTabEdit?requestId=<?= $nurseryRequest->getId() ?>">Enfant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="<?= $requestUrl ?>/user/nursery/requestTab/mumTabEdit?requestId=<?= $nurseryRequest->getId() ?>">Maman</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="<?= $requestUrl ?>/user/nursery/requestTab/dadTabEdit?requestId=<?= $nurseryRequest->getId() ?>">Papa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="<?= $requestUrl ?>/user/nursery/requestTab/healthTabEdit?requestId=<?= $nurseryRequest->getId() ?>">Santé</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="<?= $requestUrl ?>/user/nursery/requestTab/urgencyTabEdit?requestId=<?= $nurseryRequest->getId() ?>">Urgence</a>
                        </li>
                    </ul>

                <?php endif; ?>


                <div class="border rounded-bottom-sm border-top-0">
                    <div class="p-3">
                        <form class="generic-form" action="<?= $requestUrl ?>/user/nursery/requestEdit" method="POST">
                            <input id="id" type="hidden" name="id" value="<?= $nurseryRequest->getId() ?>" />
                            <input id="kidId" type="hidden" name="kidId" value="<?= $nurseryRequest->getKidId() ?>" />

                            <?php if($isNew == true): ?>

                            <div class="form-group form-group-icon">
                                <input id="firstName" name="firstName" type="text" class="form-control border"
                                    placeholder="Prénom de l'enfant:" data-required data-name="Prénom"
                                    value="<?= $kidPerson->getFirstName() ?>" /><br>
                            </div>
                            <div class="form-group form-group-icon">
                                <input id="lastName" name="lastName" type="text" class="form-control border"
                                    placeholder="Nom de l'enfant:" data-required data-name="Nom"
                                    value="<?= $kidPerson->getLastName() ?>" /><br>
                            </div>
                            <div class="form-group form-group-icon">
                                <input id="mumFirstName" name="mumFirstName" type="text" class="form-control border"
                                    placeholder="Prénom de Maman:" data-required data-name="mumFirstName"
                                    value="<?= $mumPerson->getFirstName() ?>" /><br>
                            </div>
                            <div class="form-group form-group-icon">
                                <input id="mumLastName" name="mumLastName" type="text" class="form-control border"
                                    placeholder="Nom de Maman:" data-required data-name="mumLastName"
                                    value="<?= $mumPerson->getFirstName() ?>" /><br>
                            </div>
                            <div class="form-group form-group-icon">
                                <input id="dadFirstName" name="dadFirstName" type="text" class="form-control border"
                                    placeholder="Prénom de Papa:" data-required data-name="dadFirstName"
                                    value="<?= $dadPerson->getFirstName() ?>" /><br>
                            </div>
                            <div class="form-group form-group-icon">
                                <input id="dadLastName" name="dadLastName" type="text" class="form-control border"
                                    placeholder="Nom de Papa:" data-required data-name="dadLastName"
                                    value="<?= $dadPerson->getLastName() ?>" /><br>
                            </div>

                            <?php else: ?>
                            <div class="row">
                                <div class="col-sm-3">Enfant:</div>
                                <div class="col-sm-9"><?= $kidPerson->getFirstName()." ".$kidPerson->getLastName() ?></div>

                                <div class="col-sm-3">Parents</div>
                                <div class="col-sm-9">
                                    <p>Madame <?= $mumPerson->getFirstName()." ".$mumPerson->getLastName() ?></p>
                                    <p>Monsieur <?= $dadPerson->getFirstName()." ".$dadPerson->getLastName() ?></p>
                                </div>
                            </div>
                            <div class="form-group">
                                <?php endif; ?>

                                <div class="form-group form-group-icon">
                                <input id="entryDate" name="entryDate" type="text" class="form-control border"
                                    placeholder="Date d'entrée:" data-required data-name="entryDate"
                                    value="<?= $nurseryRequest->getEntryDate() ?>" />
                                </div>
                                <div class="form-group form-group-icon">
                                <input id="cafNumber" name="cafNumber" type="text" class="form-control border"
                                    placeholder="Numéro de la caf:" data-required data-name="cafNumber"
                                    value="<?= $nurseryRequest->getCafNumber() ?>" />
                                </div>
                                <?php if($userSession->isAdmin() == true): ?>
                                <label for="cafNumber">Statut de la demande :</label><br>
                                <input type="radio" id="enCours" name="groupeSelect">
                                <label for="enCours">En cours</label>
                                <input type="radio" id="acceptee" name="groupeSelect">
                                <label for="acceptee">Acceptée</label><br />
                                <input type="radio" id="refusee" name="groupeSelect">
                                <label for="refusee">Refusée</label>
                        
                            <?php endif; ?>
                            <!--<?= $nurseryRequest->getStatusReq() ?><br>-->

                            <div class="form-group">
                                <?php if($isNew == true): ?>
                                    <button type="submit" class="btn btn-danger text-uppercase w-100">Créer</button>
                                <?php else: ?>
                                    <button type="submit" class="btn btn-danger text-uppercase w-100">Sauvegarder</button>
                                <?php endif; ?>
                            </div>
                            <button class="btn btn-danger text-uppercase w-100" value="Retour"
                                onclick="history.go(-1)">
                                Retour
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>