<!-- Affichage du template lié à la vue -->

    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !
        </h3>
        <p><?= $errorMessage ?></p>
    </aside>
        <section class="py-8 py-md-10">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 offset-lg-3 col-lg-6">
                        <div class="mb-4 mb-sm-0">
                            <div class="bg-warning rounded-top p-2">
                                <h1 class="text-white font-weight-bold mb-0 ml-2">Editer votre profil</h1>
                            </div>

                            <div class="border rounded-bottom-sm border-top-0">
                                <div class="p-3">
                                <form class="generic-form" action="<?= $requestUrl ?>/user/profile" method="POST">

                                    <div class="form-group form-group-icon">
                                        <input id="firstName" name="firstName" type="text" class="form-control border"
                                            placeholder="firstName" data-required data-name="Prénom"
                                            value="<?= $currentUser->getFirstName() ?>" />
                                    </div>
                                    <div class="form-group form-group-icon">
                                        <input id="lastName" name="lastName" type="text" class="form-control border"
                                            placeholder="lastName" data-required data-name="Nom"
                                            value="<?= $currentUser->getLastName() ?>" />
                                    </div>
                                    <div class="form-group form-group-icon">
                                        <input id="address" name="address" type="text" class="form-control border"
                                            placeholder="address" data-required data-name="address"
                                            value="<?= $currentUser->getAddress() ?>" />
                                    </div>
                                    <div class="form-group form-group-icon">
                                        <input id="city" name="city" type="text" class="form-control border"
                                            placeholder="city" data-required data-name="city"
                                            value="<?= $currentUser->getCity() ?>" />
                                    </div>
                                    <div class="form-group form-group-icon">
                                        <input id="zipCode" name="zipCode" type="text" class="form-control border"
                                            placeholder="zipCode" data-required data-name="zipCode"
                                            value="<?= $currentUser->getZipCode() ?>" />
                                    </div>
                                    <div class="form-group form-group-icon">
                                        <input id="phone" name="phone" type="text" class="form-control border"
                                            placeholder="phone" data-required data-name="phone"
                                            value="<?= $currentUser->getPhone() ?>" />
                                    </div>
                                    <div class="form-group form-group-icon">
                                        <input id="email" name="email" type="text" class="form-control border"
                                            placeholder="email" data-required data-name="email"
                                            value="<?= $currentUser->getEmail() ?>" />
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-danger text-uppercase w-100">Sauvgarder</button>
                                    </div>
                                    </form>
                                    <div class="form-group">
                                        <a href="<?= $requestUrl ?>">
                                            <button class="btn btn-danger text-uppercase w-100">Retour</button>
                                        <a />
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

<!--<button class="btn btn-secondary" type="reset" name="resetButton">Retour</button>-->