<!-- Affichage du template lié à la vue -->
<table class="generic-table meal-list">
    <tbody>

        <h2>Connection avec un compte d'utilisateur</h2>
        <form action="<?= $requestUrl ?>/user/login" method="POST">
        <fieldset>
            <legend>Informations d'authentification</legend>
                <label for="email">E-mail :</label><br>
                <input id="email" name="email" type="text" value=""><br>
                <label for="password">Mot de passe :</label><br>
                <input id="password" name="password" type="password"><br>
                <hr>
                <button class="connection" name="submitButton" type="submit">Connexion</button>
                <button class="cancel" name="cxlButton" type="submit">Annuler</button>
        </fieldset>
        </form>
