<!-- Affichage du template lié à la vue -->
<table class="generic-table meal-list">
    <tbody>

        <h2>Connection avec un compte d'utilisateur</h2>
        <form action="<?= $requestUrl ?>/user/login" method="POST">
        <fieldset>
            <legend>Informations d'authentification</legend>
                <div class="form-group">
                    <label for="email">E-mail :</label><br>
                    <input id="email" class="form-control" name="email" type="text" value=""><br>
                    <label for="password">Mot de passe :</label><br>
                    <input id="password" class="form-control" name="password" type="password"><br>
                    <button class="btn btn-primary" name="submitButton" type="submit">Connexion</button>
                    <button class="btn btn-secondary" name="cxlButton" type="submit">Annuler</button>
                    </div>
        </fieldset>
        </form>
