

<section class="py-8 py-md-10">
  <div class="container">
    <div class="row">
    <div class="col-sm-6 offset-lg-3 col-lg-6">
        <div class="mb-4 mb-sm-0">
          <div class="bg-warning rounded-top p-2">
            <h3 class="text-white font-weight-bold mb-0 ml-2">S'identifier</h3>
          </div>
  
          <div class="border rounded-bottom-sm border-top-0">
            <div class="p-3">
              <form action="<?= $requestUrl ?>/user/login" method="POST">
                <div class="form-group form-group-icon">
                  <input id="email" name="email" type="text" class="form-control border" placeholder="Email">
                </div>

                <div class="form-group form-group-icon">
                  <input id="password" name="password" type="password" class="form-control border" placeholder="Mot de passe">
                </div>

                <div class="form-group">
                  <button type="submit" class="btn btn-danger text-uppercase w-100">Se connecter</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>