<!-- Affichage du template lié à la vue -->
<h1>Formulaire d'inscription</h1>

<form class="generic-form" action="<?= $requestUrl ?>/user/signin" method="POST">
    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !</h3>
        <p><?= $errorMessage ?></p>
    </aside>
    
    <fieldset>
        <legend>
            <h2>Coordonnées personelles</h2>
        </legend>
        <div class="form-group">
        <label for="firstName">Prénom :</label><br>
            <input id="firstName" class="form-control" type="text" name="firstName" data-required data-name="Prénom" value="<?= $firstName ?>"/><br>
            <label for="lastName">Nom :</label><br>
            <input id="lastName" class="form-control" type="text" name="lastName" data-required data-name="Nom" value="<?= $lastName ?>"/><br>
            <label for="address">Adresse :</label><br>
            <input name="address" class="form-control" id="address"/><br>
            <label for="city">Ville :</label><br>
            <input name="city" class="form-control" id="city"/><br>
            <label for="zipCode">Code Postal :</label><br>
            <input id="zipCode" class="form-control" name="zipCode" type="text" maxlength="5"/><br>
            <label for="phone">Téléphone :</label><br>
            <input id="phone" class="form-control" name="phone" type="text" maxlength="10" data-type="number"/><br>
            <label for="email">E-mail :</label><br>
            <input id="email" class="form-control" type="text" name="email" data-required data-name="E-mail" value="<?= $email ?>"/><br>
            <label for="password">Mot de passe :</label><br>
            <input id="password" class="form-control" type="password" name="password" data-required data-name="Mot de passe" value="<?= $password ?>"/><br>
            </div>
            <button class="btn btn-primary" type="submit" name="submitButton">S'enregistrer</button>
    </fieldset>    
</form>