<!-- Affichage du template lié à la vue -->
<table class="generic-table meal-list">

    <tbody>
        <h1>Formulaire d'inscription</h1>
        <fieldset>
            <legend>
                <h2>Coordonnées personelles</h2>
            </legend>
            <form action="<?= $requestUrl ?>/user/signin" method="POST">
                <label for="lastName">Nom :</label><br>
                <input name="lastName" type="text" /><br>
                <label for="firstName">Prénom :</label><br>
                <input name="firstName" type="text" /><br>
                <label for="address">Adresse :</label><br>
                <input name="address" id="address" /><br>
                <label for="city">Ville :</label><br>
                <input name="city" id="city" /><br>
                <label for="zipCode">Code Postal :</label><br>
                <input id="zipCode" name="zipCode" type="text" maxlength="5" /><br>
                <label for="phone">Téléphone :</label><br>
                <input id="phone" name="phone" type="text" maxlength="10" /><br>
                <label for="email">E-mail :</label><br>
                <input id="email" name="email" type="text" /><br>
                <label for="password">Mot de passe :</label><br>
                <input id="password" name="password" type="password" /><br>
                <button class="validation" type="submit" name="submitButton">S'enregistrer</button>
            </form>
        </fieldset>    
    </tbody>
</table>